spring:
  application:
    name: joaostore

  # debug: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/joaostore
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
