spring:
  application:
    name: joaostore

  # debug: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:file:~/joaostore;AUTO_SERVER=true
    username: sa
    password: ""
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: embedded
      schema-locations: optional:classpath:sql/schema.sql
      data-locations: optional:classpath:sql/data.sql

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
